- name: Restart the Loki service
  service:
    name: loki
    state: restarted
  listen: event_restart_alertmanager

- name: Reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload