---
- hosts: node_exporter
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter

- hosts: prometheus
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_blackbox_exporter
    - prometheus
    - alertmanager

- hosts: grafana
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - grafana
    - prometheus_node_exporter
    - grafana_loki