---
- hosts: node_exporter
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter
    - grafana

- hosts: prometheus
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_blackbox_exporter
    - prometheus